name: tumble
description: Tumble for Kronox

publish_to: 'none'

version: 3.1.4+36

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  darq: ^2.0.0
  uuid: ^4.1.0
  syncfusion_localizations: ^23.1.39
  equatable: ^2.0.5
  freezed: ^2.4.3
  cupertino_icons: ^1.0.5
  build_runner: ^2.4.6
  build_runner_core: ^7.2.9
  sembast: ^3.2.0+1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  permission_handler: ^11.0.1
  lottie: ^2.6.0
  intl: ^0.18.1
  flutter_spinkit: any
  path_provider: ^2.0.9
  syncfusion_flutter_calendar: ^23.1.39
  dart_extensions: ^2.2.0
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.4.1
  json_annotation: ^4.5.0
  flutter_secure_storage: ^9.0.0
  awesome_notifications: ^0.8.2
  url_launcher: ^6.1.5
  flutter_colorpicker: ^1.0.3
  html_unescape: ^2.0.0
  shimmer_animation: ^2.1.0+1
  auto_size_text: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  bloc: ^8.1.0
  collection: ^1.16.0
  path: ^1.8.1
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  drift_dev: ^2.12.1
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0

flutter:
  generate: true
  assets:
    - assets/animations/lottie_success_burst.json
    - assets/images/cardBanner.png
    - assets/images/ic_launcher.png
    - assets/images/detailsSplitter.png
    - assets/school_logos/hkr_logo.png
    - assets/school_logos/ltu_logo.png
    - assets/school_logos/mau_logo.png
    - assets/school_logos/oru_logo.png
    - assets/school_logos/hb_logo.png
    - assets/school_logos/hig_logo.png
    - assets/school_logos/hv_logo.png
    - assets/school_logos/mdh_logo.png
    - assets/school_logos/sh_logo.png
    - assets/images/kronox_logo.png
    - assets/images/canvas_logo.png
    - assets/images/ladok_logo.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_black_italic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/roboto_black.ttf
          weight: 900
        - asset: assets/fonts/roboto_bold_italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_light_italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto_light.ttf
          weight: 300
        - asset: assets/fonts/roboto_medium_italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto_medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_thin_italic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/roboto_thin.ttf
          weight: 100
        - asset: assets/fonts/roboto.ttf
          weight: 400
          style: italic

  uses-material-design: true
