name: tumble
description: Tumble for Kronox

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.1
  darq: ^1.2.1
  uuid: ^3.0.6
  syncfusion_localizations: ^20.2.45
  equatable: ^2.0.5
  freezed: any
  cupertino_icons: ^1.0.5
  build_runner: ^2.1.11
  sembast: ^3.2.0+1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  permission_handler: ^9.2.0
  lottie: ^1.4.0
  intl: ^0.17.0
  flutter_spinkit: any
  path_provider: ^2.0.9
  syncfusion_flutter_calendar: ^20.2.40
  dart_extensions: ^2.2.0
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  flutter_secure_storage: ^5.0.2
  awesome_notifications: ^0.6.21
  url_launcher: ^6.1.5
  flutter_colorpicker: ^1.0.3
  html_unescape: ^2.0.0
  shimmer_animation: ^2.1.0+1
  auto_size_text: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  bloc: ^8.1.0
  collection: ^1.16.0
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_native_splash: ^2.2.6

  drift_dev: ^1.5.2
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0

flutter_native_splash:
  image: assets/images/tumbleAppLogo.png
  color: "f7f7f7"

flutter:
  generate: true
  assets:
    - assets/animations/lottie_success_burst.json
    - assets/images/cardBanner.png
    - assets/images/tumbleAppLogo.png
    - assets/images/detailsSplitter.png
    - assets/school_logos/hkr_logo.png
    - assets/school_logos/ltu_logo.png
    - assets/school_logos/mau_logo.png
    - assets/school_logos/oru_logo.png
    - assets/school_logos/hb_logo.png
    - assets/school_logos/hig_logo.png
    - assets/school_logos/hv_logo.png
    - assets/school_logos/mdh_logo.png
    - assets/school_logos/sh_logo.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_black_italic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/roboto_black.ttf
          weight: 900
        - asset: assets/fonts/roboto_bold_italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_light_italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto_light.ttf
          weight: 300
        - asset: assets/fonts/roboto_medium_italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto_medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_thin_italic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/roboto_thin.ttf
          weight: 100
        - asset: assets/fonts/roboto.ttf
          weight: 400
          style: italic

  uses-material-design: true
